name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu, macos, windows ]
        build_type: [ Debug ]
        arch: [ x86_64, arm64 ]
        exclude:
          - os: ubuntu
            arch: arm64
          - os: windows
            arch: arm64

    runs-on: ${{ matrix.os }}-latest

    env:
      CMAKE_CONFIG_EXTRA: ${{ matrix.os == 'macos' && format('-DCMAKE_OSX_ARCHITECTURES={0}', matrix.arch) || '' }}

    steps:
    - uses: actions/checkout@v3

    - if: matrix.os == 'ubuntu'
      name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DBUILD_SHARED_LIBS=FALSE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ env.CMAKE_CONFIG_EXTRA }}

    - name: Build
      working-directory: ${{ github.workspace }}/build
      run: cmake --build . --config ${{ matrix.build_type }}
